# When an error occurs, or exception as we call it, Python will normally stop and generate an error message.
# These exceptions can be handled using the try statement:

# The try block will generate an exception, because x is not defined:
#The try block will generate an error, because x is not defined:

try:
  print(x)
except:
  print("An exception occurred")
